Repository Fujicracy/fuji-v2, pull requests merged in 2023-05, with the labels that each got.

#487 Vault rounding and complementary debt functions
  packages/protocol/src/abstracts/BaseVault.sol
  packages/protocol/src/interfaces/IVault.sol
  packages/protocol/src/routers/ConnextRouter.sol
  packages/protocol/src/vaults/borrowing/BorrowingVault.sol
  packages/protocol/src/vaults/borrowing/BorrowingVaultFactory.sol
  packages/protocol/src/vaults/yield/YieldVault.sol
  packages/protocol/test/mocking/MockRoutines.sol
  packages/protocol/test/mocking/vaults/Vault.t.sol
Labels: Smart Contracts

#495 Vaults cannot reach deposit cap
  packages/protocol/src/abstracts/BaseVault.sol
  packages/protocol/test/mocking/MockRoutines.sol
  packages/protocol/test/mocking/vaults/Vault.t.sol
Labels: Bug, Smart Contracts

#497 UI issues v4
  packages/frontend/components/Borrow/TransactionModal.tsx
  packages/frontend/components/Markets/BestLabel.tsx
  packages/frontend/components/Markets/Markets.tsx
  packages/frontend/components/Markets/MarketsTable.tsx
  packages/frontend/components/Markets/MarketsTableRow.tsx
  packages/frontend/components/Positions/LiquidationBox.tsx
  packages/frontend/components/Positions/MyPositions.tsx
  packages/frontend/components/Positions/MyPositionsBorrowTable.tsx
  packages/frontend/components/Positions/PositionYieldsModal.tsx
  packages/frontend/components/Shared/AccountModal.tsx
  packages/frontend/components/Shared/AddTokenButton.tsx
  packages/frontend/components/Shared/BorrowLendingTabNavigation.tsx
  packages/frontend/components/Shared/Header/Banner.tsx
  packages/frontend/components/Shared/Header/Header.tsx
  packages/frontend/components/Shared/Icons/LinkIcon.tsx
  packages/frontend/components/Shared/Icons/NotFoundIcon.tsx
  packages/frontend/components/Shared/TabChip.tsx
  packages/frontend/components/Shared/Tooltips/InfoTooltip.tsx
  packages/frontend/helpers/markets.ts
  packages/frontend/pages/404.tsx
  packages/frontend/pages/500.tsx
  packages/frontend/pages/_app.tsx
  packages/frontend/pages/index.tsx
  packages/frontend/pages/lend.tsx
  packages/frontend/pages/my-positions.tsx
  packages/frontend/public/assets/images/errors/4.svg
  packages/frontend/public/assets/images/errors/somethingWentWrong.svg
  packages/frontend/public/assets/images/notifications/error.svg
  packages/frontend/public/assets/images/notifications/info.svg
  packages/frontend/public/assets/images/shared/lightning.png
  packages/frontend/public/assets/images/shared/wallet.svg
  packages/frontend/public/assets/images/transactions/END.gif
  packages/frontend/public/assets/images/transactions/ERROR.gif
  packages/frontend/public/assets/images/transactions/RIDE.gif
  packages/frontend/public/assets/images/transactions/START.gif
  packages/frontend/store/auth.store.ts
  packages/frontend/store/history.store.ts
  packages/frontend/styles/theme.ts
Labels: Front End

#506 Frontend known issues
  packages/frontend/components/Borrow/Borrow.tsx
  packages/frontend/components/Borrow/Button.tsx
  packages/frontend/components/Borrow/Overview/Container.tsx
  packages/frontend/components/Borrow/Overview/Details.tsx
  packages/frontend/components/Borrow/Overview/VaultsMenu.tsx
  packages/frontend/components/Markets/MarketsTable.tsx
  packages/frontend/components/Shared/AccountModal.tsx
  packages/frontend/components/Shared/Header/Header.tsx
  packages/frontend/helpers/balances.ts
  packages/frontend/next.config.js
  packages/frontend/public/assets/images/transactions/ERROR.gif
  packages/frontend/store/borrow.store.ts
  packages/frontend/store/history.store.ts
  packages/sdk/src/constants/vaults.ts
Labels: Front End

#499 Rebalance breaks ltv
  packages/protocol/src/LiquidationManager.sol
  packages/protocol/src/RebalancerManager.sol
  packages/protocol/src/interfaces/IFujiOracle.sol
  packages/protocol/src/vaults/borrowing/BorrowingVault.sol
  packages/protocol/test/mocking/MockingSetup.sol
  packages/protocol/test/mocking/vaults/Vault.t.sol
  packages/protocol/test/mocking/vaults/VaultLiquidation.t.sol
  packages/protocol/test/mocking/vaults/VaultRebalancing.t.sol
Labels: Bug, Smart Contracts

#425 Multiple router conditions
  packages/protocol/script/02_SignBorrow.s.sol
  packages/protocol/script/03_PrintBorrows.s.sol
  packages/protocol/src/Chief.sol
  packages/protocol/src/abstracts/BaseRouter.sol
  packages/protocol/src/abstracts/BaseVault.sol
  packages/protocol/src/interfaces/IChief.sol
  packages/protocol/src/interfaces/IVaultPermissions.sol
  packages/protocol/src/libraries/LibSigUtils.sol
  packages/protocol/src/routers/ConnextRouter.sol
  packages/protocol/src/vaults/VaultPermissions.sol
  packages/protocol/src/vaults/borrowing/BorrowingVault.sol
  packages/protocol/src/vaults/yield/YieldVault.sol
  packages/protocol/test/forking/ForkingSetup.sol
  packages/protocol/test/forking/goerli/ConnextRouter.t.sol
  packages/protocol/test/forking/optimism-goerli/ConnextRouter.t.sol
  packages/protocol/test/forking/polygon/SimpleRouter.t.sol
  packages/protocol/test/mocking/MockingSetup.sol
  packages/protocol/test/mocking/routers/SimpleRouter.t.sol
  packages/protocol/test/mocking/vaults/VaultPausable.t.sol
  packages/protocol/test/mocking/vaults/VaultPermissions.t.sol
  packages/protocol/test/simulations/AttackPermits.t.sol
Labels: Bug, Smart Contracts

#479 Frontend testing setup
  .gitignore
  packages/frontend/README.md
  packages/frontend/components/Onboarding/ExploreCarousel.tsx
  packages/frontend/components/Onboarding/SafetyNoticeModal.tsx
  packages/frontend/components/Shared/AccountModal.tsx
  packages/frontend/components/Shared/ChainSelect.tsx
  packages/frontend/components/Shared/Header/BalanceAddon.tsx
  packages/frontend/components/Shared/Header/Header.tsx
  packages/frontend/package.json
  packages/frontend/tests/e2e/.eslintrc.js
  packages/frontend/tests/e2e/.eslintrc.json
  packages/frontend/tests/e2e/reference/borrow-spec.ts
  packages/frontend/tests/e2e/reference/metamask-spec.ts
  packages/frontend/tests/e2e/specs/account-spec.ts
  yarn.lock
Labels: Front End

#403 Macro findings critical high
  packages/protocol/script/02_SignBorrow.s.sol
  packages/protocol/script/03_PrintBorrows.s.sol
  packages/protocol/src/Chief.sol
  packages/protocol/src/abstracts/BaseRouter.sol
  packages/protocol/src/abstracts/BaseVault.sol
  packages/protocol/src/interfaces/IChief.sol
  packages/protocol/src/interfaces/IVaultPermissions.sol
  packages/protocol/src/interfaces/connext/IConnext.sol
  packages/protocol/src/libraries/LibSigUtils.sol
  packages/protocol/src/routers/ConnextHandler.sol
  packages/protocol/src/routers/ConnextRouter.sol
  packages/protocol/src/routers/SimpleRouter.sol
  packages/protocol/src/vaults/VaultPermissions.sol
  packages/protocol/src/vaults/borrowing/BorrowingVault.sol
  packages/protocol/src/vaults/borrowing/BorrowingVaultFactory.sol
  packages/protocol/src/vaults/yield/YieldVault.sol
  packages/protocol/test/forking/ForkingSetup.sol
  packages/protocol/test/forking/goerli/ConnextRouter.t.sol
  packages/protocol/test/forking/mainnet/CompoundV3.t.sol
  packages/protocol/test/forking/mainnet/DenialOfService.t.sol
  packages/protocol/test/forking/optimism-goerli/ConnextRouter.t.sol
  packages/protocol/test/forking/polygon/LiquidationManagerPolygon.t.sol
  packages/protocol/test/forking/polygon/SimpleRouter.t.sol
  packages/protocol/test/mocking/MockingSetup.sol
  packages/protocol/test/mocking/access/AccessControl.t.sol
  packages/protocol/test/mocking/routers/SimpleRouter.t.sol
  packages/protocol/test/mocking/vaults/Vault.t.sol
  packages/protocol/test/mocking/vaults/VaultAccessControl.t.sol
  packages/protocol/test/mocking/vaults/VaultFactoryDeployment.t.sol
  packages/protocol/test/mocking/vaults/VaultLiquidation.t.sol
  packages/protocol/test/mocking/vaults/VaultPausable.t.sol
  packages/protocol/test/mocking/vaults/VaultPermissions.t.sol
  packages/protocol/test/mocking/vaults/VaultRebalancing.t.sol
  packages/protocol/test/simulations/AttackDoubleDeposits.sol
  packages/protocol/test/simulations/AttackPermits.t.sol
  packages/protocol/test/utils/Routines.sol
Labels: Bug, Smart Contracts

#507 Frontend market testing
  packages/frontend/components/Borrow/Box/TokenCard.tsx
  packages/frontend/components/Markets/BestLabel.tsx
  packages/frontend/components/Markets/MarketFiltersHeader.tsx
  packages/frontend/components/Markets/Markets.tsx
  packages/frontend/components/Markets/MarketsTable.tsx
  packages/frontend/components/Markets/MarketsTableRow.tsx
  packages/frontend/helpers/markets.ts
  packages/frontend/public/assets/images/shared/search.svg
  packages/frontend/tests/e2e/reference/borrow-spec.ts
  packages/frontend/tests/e2e/reference/metamask-spec.ts
  packages/frontend/tests/e2e/specs/account-spec.ts
  packages/frontend/tests/e2e/specs/markets-spec.ts
  packages/frontend/tests/e2e/support.js
Labels: Front End

#494 3-chain interactions
  packages/frontend/README.md
  packages/frontend/components/Borrow/Borrow.tsx
  packages/frontend/components/Borrow/Box/Box.tsx
  packages/frontend/components/Borrow/Box/ChainSelect.tsx
  packages/frontend/components/Borrow/Box/TokenCard.tsx
  packages/frontend/components/Borrow/Button.tsx
  packages/frontend/components/Borrow/Fees.tsx
  packages/frontend/components/Borrow/Overview/Overview.tsx
  packages/frontend/components/Borrow/Overview/Summary/SummaryCardItem.tsx
  packages/frontend/components/Borrow/Routing/RouteCard.tsx
  packages/frontend/components/Borrow/TransactionModal.tsx
  packages/frontend/components/Shared/AccountModal/AccountModal.tsx
  packages/frontend/components/Shared/AccountModal/HistoryItem.tsx
  packages/frontend/components/Shared/Balance.tsx
  packages/frontend/components/Shared/ConfirmTransactionModal.tsx
  packages/frontend/components/Shared/ConfirmationTransaction/RouteBox.tsx
  packages/frontend/components/Shared/Header/Header.tsx
  packages/frontend/constants/common.ts
  packages/frontend/drawio.svg
  packages/frontend/helpers/history.ts
  packages/frontend/helpers/routing.ts
  packages/frontend/helpers/transactions.ts
  packages/frontend/helpers/values.ts
  packages/frontend/public/assets/images/logo/connext-title.svg
  packages/frontend/store/borrow.store.ts
  packages/frontend/store/history.store.ts
  packages/sdk/README.md
  packages/sdk/package.json
  packages/sdk/src/Previews.ts
  packages/sdk/src/constants/common.ts
  packages/sdk/src/entities/AbstractCurrency.ts
  packages/sdk/src/entities/Address.ts
  packages/sdk/src/enums/OperationType.ts
  packages/sdk/src/enums/PreviewName.ts
  packages/sdk/src/enums/index.ts
  packages/sdk/src/functions/encodeActionArgs.ts
  packages/sdk/src/functions/getPreviewActions.ts
  packages/sdk/src/functions/getPreviewRoutingDetails.ts
  packages/sdk/src/functions/index.ts
  packages/sdk/src/functions/xChainArguments.ts
  packages/sdk/src/types/BridgeFee.ts
  packages/sdk/src/types/MetaRoutingResult.ts
  packages/sdk/src/types/PreviewParams.ts
  packages/sdk/src/types/PreviewResult.ts
  packages/sdk/src/types/index.ts
  packages/sdk/test/Sdk.test.ts
  packages/sdk/test/entities/Token.test.ts
  yarn.lock
Labels: Front End, Sdk

#521 Login improvements
  packages/frontend/components/Onboarding/DisclaimerModal.tsx
  packages/frontend/components/Onboarding/ExploreCarousel.tsx
  packages/frontend/components/Shared/Header/AddressAddon.tsx
  packages/frontend/components/Shared/Header/Header.tsx
  packages/frontend/helpers/auth.ts
  packages/frontend/pages/_app.tsx
  packages/frontend/store/auth.store.ts
  packages/frontend/store/history.store.ts
Labels: Front End

#508 M-4 Max function compliance with EIP4626
  packages/protocol/src/abstracts/BaseVault.sol
  packages/protocol/src/vaults/borrowing/BorrowingVault.sol
  packages/protocol/test/mocking/vaults/VaultPausable.t.sol
Labels: Bug, Smart Contracts

#525 Markets store
  packages/frontend/README.md
  packages/frontend/components/Borrow/Borrow.tsx
  packages/frontend/components/Borrow/Header.tsx
  packages/frontend/components/Borrow/Overview/Details.tsx
  packages/frontend/components/Markets/BestLabel.tsx
  packages/frontend/components/Markets/MarketFiltersHeader.tsx
  packages/frontend/components/Markets/MarketsTable.tsx
  packages/frontend/components/Markets/MarketsTableRow.tsx
  packages/frontend/components/Positions/MyPositionsBorrowTable.tsx
  packages/frontend/components/Shared/Table/IntegratedProviders.tsx
  packages/frontend/components/Shared/Tooltips/RebalanceTooltip.tsx
  packages/frontend/components/Shared/Tooltips/index.ts
  packages/frontend/helpers/markets.ts
  packages/frontend/helpers/stores.ts
  packages/frontend/store/auth.store.ts
  packages/frontend/store/borrow.store.ts
  packages/frontend/store/history.store.ts
  packages/frontend/store/markets.store.ts
  packages/frontend/store/positions.store.ts
Labels: Front End

#526 Refactor borrow store
  packages/frontend/components/Borrow/Borrow.tsx
  packages/frontend/components/Borrow/Box/Box.tsx
  packages/frontend/components/Borrow/Box/CurrencyCard.tsx
  packages/frontend/components/Borrow/Button.tsx
  packages/frontend/components/Borrow/Fees.tsx
  packages/frontend/components/Borrow/Overview/Details.tsx
  packages/frontend/components/Borrow/Overview/Overview.tsx
  packages/frontend/components/Borrow/Overview/Title.tsx
  packages/frontend/components/Borrow/Overview/VaultsMenu.tsx
  packages/frontend/components/Borrow/Routing/RoutingModal.tsx
  packages/frontend/components/Borrow/Wrapper.tsx
  packages/frontend/components/Shared/ConfirmTransactionModal.tsx
  packages/frontend/components/Shared/ConfirmationTransaction/AssetBox.tsx
  packages/frontend/components/Shared/Tooltips/ProvidersTooltip.tsx
  packages/frontend/constants/common.ts
  packages/frontend/helpers/assets.ts
  packages/frontend/helpers/balances.ts
  packages/frontend/helpers/errors.ts
  packages/frontend/helpers/history.ts
  packages/frontend/helpers/positions.ts
  packages/frontend/helpers/transactions.ts
  packages/frontend/pages/borrow.tsx
  packages/frontend/pages/my-positions/[pid].tsx
  packages/frontend/store/borrow.store.ts
  packages/frontend/store/models/Position.ts
  packages/frontend/store/positions.store.ts
  packages/sdk/src/Sdk.ts
  packages/sdk/src/entities/BorrowingVault.ts
  packages/sdk/src/types/LendingProvider.ts
  packages/sdk/test/Sdk.test.ts
Labels: Front End, Sdk

#532 Remove redundant xreceive slippage check
  packages/protocol/src/routers/ConnextRouter.sol
  packages/protocol/test/forking/ForkingSetup.sol
  packages/protocol/test/forking/goerli/ConnextRouter.t.sol
  packages/protocol/test/forking/optimism-goerli/ConnextRouter.t.sol
Labels: Smart Contracts

#533 Sender param in cross-tranfer with call
  packages/protocol/src/routers/ConnextRouter.sol
  packages/protocol/test/forking/goerli/ConnextRouter.t.sol
  packages/protocol/test/forking/optimism-goerli/ConnextRouter.t.sol
Labels: Smart Contracts

#552 Remove vaults depositcap
  packages/protocol/src/abstracts/BaseVault.sol
  packages/protocol/src/interfaces/IVault.sol
  packages/protocol/test/mocking/vaults/Vault.t.sol
  packages/protocol/test/mocking/vaults/VaultAccessControl.t.sol
Labels: Smart Contracts

#534 3-chain improvements
  packages/frontend/components/Borrow/Borrow.tsx
  packages/frontend/components/Borrow/Box/TokenCard.tsx
  packages/frontend/constants/notifications.ts
  packages/frontend/helpers/assets.ts
  packages/frontend/helpers/errors.ts
  packages/frontend/helpers/history.ts
  packages/frontend/helpers/transactions.ts
  packages/frontend/store/history.store.ts
  packages/sdk/package.json
  packages/sdk/src/Nxtp.ts
  packages/sdk/src/Previews.ts
  packages/sdk/src/Sdk.ts
  packages/sdk/src/functions/index.ts
  packages/sdk/src/functions/waitForTransaction.ts
  yarn.lock
Labels: Front End

#543 Error gif changed
  packages/frontend/public/assets/images/transactions/ERROR.gif
Labels: Front End

#536 Macro post review critical-high
  packages/protocol/src/abstracts/BaseRouter.sol
  packages/protocol/src/abstracts/BaseVault.sol
  packages/protocol/src/routers/ConnextHandler.sol
  packages/protocol/src/routers/ConnextRouter.sol
  packages/protocol/src/routers/SimpleRouter.sol
  packages/protocol/src/vaults/borrowing/BorrowingVault.sol
  packages/protocol/test/forking/arbitrum/AaveV3.t.sol
  packages/protocol/test/forking/arbitrum/DForceArbitrum.t.sol
  packages/protocol/test/forking/arbitrum/FlasherBalancerArbitrum.t.sol
  packages/protocol/test/forking/arbitrum/HundredArbitrum.t.sol
  packages/protocol/test/forking/arbitrum/RadiantArbitrum.t.sol
  packages/protocol/test/forking/arbitrum/WePiggyArbitrum.t.sol
  packages/protocol/test/forking/gnosis/AgaveGnosis.t.sol
  packages/protocol/test/forking/gnosis/FlasherBalancerGnosis.t.sol
  packages/protocol/test/forking/gnosis/HundredGnosis.t.sol
  packages/protocol/test/forking/goerli/ConnextRouter.t.sol
  packages/protocol/test/forking/mainnet/AaveV2.t.sol
  packages/protocol/test/forking/mainnet/AaveV3.t.sol
  packages/protocol/test/forking/mainnet/CompoundV2.t.sol
  packages/protocol/test/forking/mainnet/CompoundV3.t.sol
  packages/protocol/test/forking/mainnet/DForce.t.sol
  packages/protocol/test/forking/mainnet/Euler.t.sol
  packages/protocol/test/forking/mainnet/FlasherBalancer.t.sol
  packages/protocol/test/forking/mainnet/FlasherEuler.t.sol
  packages/protocol/test/forking/mainnet/MorphoAaveV2.t.sol
  packages/protocol/test/forking/mainnet/MorphoCompound.t.sol
  packages/protocol/test/forking/mainnet/UniswapV2Swapper.t.sol
  packages/protocol/test/forking/mainnet/VaultSetProviders.t.sol
  packages/protocol/test/forking/mainnet/WePiggy.t.sol
  packages/protocol/test/forking/optimism-goerli/ConnextRouter.t.sol
  packages/protocol/test/forking/optimism/AaveV3.t.sol
  packages/protocol/test/forking/optimism/DForceOptimism.t.sol
  packages/protocol/test/forking/optimism/FlasherBalancerOptimism.t.sol
  packages/protocol/test/forking/optimism/HundredOptimism.t.sol
  packages/protocol/test/forking/optimism/WePiggyOptimism.sol
  packages/protocol/test/forking/polygon/AaveV2.t.sol
  packages/protocol/test/forking/polygon/AaveV3.t.sol
  packages/protocol/test/forking/polygon/DForcePolygon.t.sol
  packages/protocol/test/forking/polygon/FlasherAaveV3.t.sol
  packages/protocol/test/forking/polygon/FlasherBalancerPolygon.t.sol
  packages/protocol/test/forking/polygon/HundredPolygon.t.sol
  packages/protocol/test/forking/polygon/LiquidationManagerPolygon.t.sol
  packages/protocol/test/forking/polygon/Ovix.t.sol
  packages/protocol/test/forking/polygon/SimpleRouter.t.sol
  packages/protocol/test/forking/polygon/VaultRebalancing.t.sol
  packages/protocol/test/forking/polygon/WePiggyPolygon.t.sol
  packages/protocol/test/mocking/vaults/VaultRebalancing.t.sol
Labels: Bug, Smart Contracts

#553 Replace for safetransfer
  packages/protocol/src/flashloans/FlasherEuler.sol
  packages/protocol/src/routers/ConnextRouter.sol
Labels: Smart Contracts

#557 Contract zero checks
  packages/protocol/src/flashloans/FlasherEuler.sol
  packages/protocol/src/vaults/borrowing/BorrowingVault.sol
Labels: Smart Contracts

#550 Routes redesign
  packages/frontend/components/Borrow/Borrow.tsx
  packages/frontend/components/Borrow/TransactionModal.tsx
  packages/frontend/components/Shared/AssetsContainer.tsx
  packages/frontend/components/Shared/ConfirmTransactionModal.tsx
  packages/frontend/components/Shared/ConfirmationTransaction/AssetBox.tsx
  packages/frontend/components/Shared/ConfirmationTransaction/RouteBox.tsx
  packages/frontend/components/Shared/RoutesSteps.tsx
  packages/frontend/helpers/history.ts
  packages/frontend/helpers/transactions.ts
Labels: Front End
