Repository Fujicracy/fuji-v2, pull requests merged in 2023-07, with the labels that each got.

#646 Position with AbstractVault
  packages/frontend/components/Lending/LendingDetails.tsx
  packages/frontend/components/Lending/LendingForm.tsx
  packages/frontend/components/Lending/LendingFormButton.tsx
  packages/frontend/components/Positions/MyPositionsTable.tsx
  packages/frontend/components/Positions/PositionYieldsModal.tsx
  packages/frontend/components/Shared/AprValue.tsx
  packages/frontend/helpers/assets.ts
  packages/frontend/store/positions.store.ts
Labels: Front End

#640 Handling borrowingvault external full debt repay
  packages/protocol/src/vaults/borrowing/BorrowingVault.sol
  packages/protocol/src/vaults/borrowing/BorrowingVault2.sol
  packages/protocol/test/forking/mainnet/DenialOfService.t.sol
  packages/protocol/test/mocking/vaults/Vault.t.sol
Labels: Smart Contracts

#614 BaseFlasher does extra abi.encode unnecessarily
  packages/protocol/src/abstracts/BaseFlasher.sol
Labels: Smart Contracts

#642 Adapt borrowingvault for payback more than owners shares
  packages/protocol/src/vaults/borrowing/BorrowingVault.sol
  packages/protocol/src/vaults/borrowing/BorrowingVault2.sol
  packages/protocol/test/mocking/vaults/Vault.t.sol
Labels: Smart Contracts

#622 Baserouter token check logic and flashloans
  packages/protocol/src/abstracts/BaseRouter.sol
  packages/protocol/src/helpers/ReentrancyGuard.sol
  packages/protocol/src/interfaces/IRouter.sol
  packages/protocol/src/routers/ConnextRouter.sol
  packages/protocol/test/forking/goerli/ConnextRouter.t.sol
  packages/protocol/test/forking/polygon/SimpleRouter.t.sol
Labels: Smart Contracts

#649 Sweep token in handler
  packages/protocol/src/routers/ConnextHandler.sol
Labels: Smart Contracts

#647 BaseVault ensure ERC compliance
  packages/protocol/src/abstracts/BaseVault.sol
  packages/protocol/test/forking/goerli/ConnextRouter.t.sol
  packages/protocol/test/mocking/vaults/VaultPermissions.t.sol
Labels: Smart Contracts

#648 Implement using SafeERC20
  packages/protocol/src/abstracts/BaseFlasher.sol
  packages/protocol/src/abstracts/BaseRouter.sol
  packages/protocol/src/abstracts/BaseVault.sol
  packages/protocol/src/flashloans/FlasherBalancer.sol
  packages/protocol/src/flashloans/FlasherEuler.sol
  packages/protocol/src/routers/ConnextHandler.sol
  packages/protocol/src/routers/ConnextRouter.sol
  packages/protocol/src/vaults/borrowing/BorrowingVault.sol
  packages/protocol/src/vaults/borrowing/BorrowingVault2.sol
  packages/protocol/src/vaults/yields/YieldVault.sol
Labels: Smart Contracts

#621 Reentrancy in connext handler failed tx execution
  packages/protocol/src/routers/ConnextHandler.sol
Labels: Smart Contracts

#635 Console errors fixes
  packages/frontend/components/App/Header/Header.tsx
  packages/frontend/components/Borrow/Box/CurrencyCard.tsx
  packages/frontend/helpers/values.ts
Labels: Front End

#639 Introduce xreceiveproxy for safer connextrouter
  packages/protocol/src/routers/ConnextRouter.sol
  packages/protocol/src/routers/XReceiveProxy.sol
  packages/protocol/test/forking/goerli/ConnextRouter.t.sol
  packages/protocol/test/forking/optimism-goerli/ConnextRouter.t.sol
Labels: Smart Contracts

#650 Router Action.DepositETH not first for flashloan and xcalls
  packages/protocol/src/abstracts/BaseRouter.sol
  packages/protocol/src/routers/ConnextRouter.sol
  packages/protocol/src/routers/SimpleRouter.sol
  packages/protocol/test/forking/goerli/ConnextRouter.t.sol
Labels: Smart Contracts

#651 Router decoding bug and revert when receiver is router
  packages/protocol/src/routers/ConnextRouter.sol
Labels: Smart Contracts

#652 Skip calls in transfers with zeroamount
  packages/protocol/src/abstracts/BaseFlasher.sol
  packages/protocol/src/abstracts/BaseRouter.sol
  packages/protocol/src/vaults/borrowing/BorrowingVault.sol
  packages/protocol/src/vaults/borrowing/BorrowingVault2.sol
Labels: Smart Contracts

#659 Dforce lib optimism to read block from iovm
  packages/protocol/deployments/optimism/DForce_Optimism
  packages/protocol/src/libraries/LibDForceOptimism.sol
  packages/protocol/src/providers/optimism/DForceOptimism.sol
Labels: Bug, Smart Contracts

#660 Deployment fixes borrowing vault and factory
  packages/protocol/src/vaults/borrowing/BorrowingVault.sol
  packages/protocol/src/vaults/borrowing/BorrowingVaultBeaconFactory.sol
  packages/protocol/src/vaults/borrowing/BorrowingVaultUpgradeable.sol
Labels: Bug, Smart Contracts

#658 Guarded launch banner and link
  packages/frontend/components/App/Header/Banner.tsx
  packages/frontend/components/App/Header/Header.tsx
  packages/frontend/components/App/Header/SocialMenu.tsx
  packages/frontend/constants/common.ts
  packages/frontend/constants/guardedLaunchAddresses.ts
  packages/frontend/helpers/errors.ts
  packages/frontend/helpers/guardedLaunch.ts
  packages/frontend/helpers/navigation.ts
Labels: Front End

#657 Connexthandler set executed storage true-false directly
  packages/protocol/src/routers/ConnextHandler.sol
Labels: Smart Contracts

#661 Withdraw more than max replaces for max
  packages/protocol/src/abstracts/BaseVault.sol
  packages/protocol/src/abstracts/BaseVaultUpgradeable.sol
  packages/protocol/src/vaults/VaultPermissions.sol
  packages/protocol/src/vaults/borrowing/BorrowingVault.sol
  packages/protocol/src/vaults/borrowing/BorrowingVaultUpgradeable.sol
  packages/protocol/test/ErrorSelectors.t.sol
  packages/protocol/test/mocking/vaults/Vault.t.sol
Labels: Bug, Smart Contracts

#667 Max digits number for confirm tx modal
  packages/frontend/components/App/Header/AccountModal/HistoryItem.tsx
  packages/frontend/components/Borrow/Box/CurrencyCard.tsx
  packages/frontend/components/Borrow/ConfirmTransaction/AssetsContainer.tsx
  packages/frontend/components/Borrow/Overview/Summary/Summary.tsx
  packages/frontend/helpers/transactions.ts
  packages/frontend/helpers/values.ts
Labels: Front End

#674 Very low balance and input fix
  packages/frontend/components/Shared/Balance.tsx
  packages/frontend/helpers/values.ts
  packages/frontend/styles/components/Borrow.module.css
Labels: Front End

#677 Precision of max payback withdraw
  packages/protocol/src/abstracts/BaseVault.sol
  packages/protocol/src/abstracts/BaseVaultUpgradeable.sol
  packages/protocol/src/vaults/borrowing/BorrowingVault.sol
  packages/protocol/src/vaults/borrowing/BorrowingVaultUpgradeable.sol
  packages/protocol/test/PrecisionMath.t.sol
  packages/protocol/test/forking/ForkingSetup2.sol
  packages/protocol/test/forking/goerli/ConnextRouterVaultIntegration.t.sol
  packages/protocol/test/mocking/vaults/Vault.t.sol
Labels: Bug, Smart Contracts

#685 Protocol/docs/audit reports
  packages/protocol/audits/2022_Nov_ComposableSecurity_Report.pdf
  packages/protocol/audits/2023_Feb_0xMacro_Report.pdf
  packages/protocol/audits/2023_Feb_HatsFinance_Report.pdf
  packages/protocol/audits/2023_June_ThreeSigma_prelim_Report.pdf
Labels: Smart Contracts

#681 Router replace amout after soft max withdrawal
  packages/protocol/src/abstracts/BaseRouter.sol
  packages/protocol/src/routers/ConnextRouter.sol
  packages/protocol/src/routers/SimpleRouter.sol
  packages/protocol/test/mocking/routers/SimpleRouter.t.sol
Labels: Bug, Smart Contracts

#666 Rebalancer manager max rebalance
  packages/protocol/src/RebalancerManager.sol
  packages/protocol/src/interfaces/IRebalancerManager.sol
  packages/protocol/test/mocking/vaults/VaultRebalancing.t.sol
Labels: Smart Contracts
