Repository Fujicracy/fuji-v2, pull requests merged in 2023-01, with the labels that each got.

#176 Update design of account modal
  packages/frontend/components/Borrow/TransactionProcessingModal.tsx
  packages/frontend/components/Form/ChainSelect.tsx
  packages/frontend/components/Layout/AccountModal.tsx
  packages/frontend/components/Layout/DiscordIcon.tsx
  packages/frontend/components/Layout/Header.tsx
  packages/frontend/components/Layout/ParameterLinks.tsx
  packages/frontend/components/Layout/Parameters.tsx
  packages/frontend/components/Snackbar.tsx
  packages/frontend/helpers/transactionInformations.ts
  packages/frontend/store/auth.slice.ts
  packages/frontend/store/history.store.ts
  packages/frontend/styles/theme.ts
Labels: Front End, Design

#181 Markets: populate data
  packages/frontend/components/Markets/DropletIcon.tsx
  packages/frontend/components/Markets/MarketsTable.tsx
  packages/frontend/components/Markets/MarketsTableRow.tsx
  packages/frontend/components/SizableTableCell.tsx
  packages/frontend/components/TokenIcon.tsx
  packages/frontend/next.config.js
  packages/frontend/store/auth.slice.ts
  packages/frontend/store/transaction.slice.ts
  packages/frontend/styles/theme.ts
  packages/sdk/src/Sdk.ts
  packages/sdk/src/types/ChainConfig.ts
Labels: Front End

#209 My positions: integration
  packages/frontend/components/Layout/Header.tsx
  packages/frontend/components/Markets/Markets.tsx
  packages/frontend/pages/my-positions.tsx
  packages/frontend/styles/theme.ts
Labels: Front End, Design

#193 Onboard modal theming
  packages/frontend/components/Form/ChainSelect.tsx
  packages/frontend/components/Layout/Header.tsx
  packages/frontend/components/Layout/Parameters.tsx
  packages/frontend/styles/globals.css
Labels: Front End, Design

#204 BaseRouter protections
  packages/protocol/src/abstracts/BaseRouter.sol
  packages/protocol/src/routers/ConnextRouter.sol
  packages/protocol/test/forking/ForkingSetup.sol
  packages/protocol/test/forking/goerli/ConnextRouter.t.sol
  packages/protocol/test/forking/optimism-goerli/ConnextRouter.t.sol
  packages/protocol/test/forking/polygon/SimpleRouter.t.sol
  packages/protocol/test/mocking/MockingSetup.sol
  packages/protocol/test/mocking/routers/SimpleRouter.t.sol
Labels: Smart Contracts

#210 Vaults lack of slippage protection
  packages/protocol/foundry.toml
  packages/protocol/src/abstracts/BaseVault.sol
  packages/protocol/src/vaults/borrowing/BorrowingVault.sol
Labels: Smart Contracts

#226 Simplify native balance check in BaseRouter
  packages/protocol/src/abstracts/BaseRouter.sol
Labels: Smart Contracts

#215 Baserouter native balance DOS
  packages/protocol/src/abstracts/BaseRouter.sol
  packages/protocol/test/mocking/routers/SimpleRouter.t.sol
Labels: Smart Contracts

#200 ForkingSetup refactor
  packages/protocol/src/interfaces/compoundV2/IComptroller.sol
  packages/protocol/src/interfaces/dforce/IGenIToken.sol
  packages/protocol/src/interfaces/dforce/IIERC20.sol
  packages/protocol/src/interfaces/dforce/IIETH.sol
  packages/protocol/src/libraries/LibDForce.sol
  packages/protocol/src/providers/arbitrum/DForceArbitrum.sol
  packages/protocol/src/providers/arbitrum/WePiggyArbitrum.sol
  packages/protocol/src/providers/mainnet/DForce.sol
  packages/protocol/src/providers/mainnet/WePiggy.sol
  packages/protocol/src/providers/optimism/DForceOptimism.sol
  packages/protocol/src/providers/optimism/WePiggyOptimism.sol
  packages/protocol/src/providers/polygon/DForcePolygon.sol
  packages/protocol/src/providers/polygon/WePiggyPolygon.sol
  packages/protocol/test/forking/ForkingSetup.sol
  packages/protocol/test/forking/arbitrum/DForceArbitrum.t.sol
  packages/protocol/test/forking/arbitrum/WePiggyArbitrum.t.sol
  packages/protocol/test/forking/mainnet/DForce.t.sol
  packages/protocol/test/forking/mainnet/FlasherEuler.t.sol
  packages/protocol/test/forking/mainnet/WePiggy.t.sol
  packages/protocol/test/forking/optimism/DForceOptimism.t.sol
  packages/protocol/test/forking/optimism/WePiggyOptimism.sol
  packages/protocol/test/forking/polygon/DForcePolygon.t.sol
  packages/protocol/test/forking/polygon/FlasherAaveV3.t.sol
  packages/protocol/test/forking/polygon/SimpleRouter.t.sol
  packages/protocol/test/forking/polygon/WePiggyPolygon.t.sol
  packages/protocol/test/utils/Routines.sol
Labels: Smart Contracts

#234 Ironbank lending provider
  packages/protocol/src/libraries/LibIronBankOptimism.sol
  packages/protocol/src/providers/mainnet/IronBank.sol
  packages/protocol/src/providers/optimism/IronBankOptimism.sol
  packages/protocol/test/forking/mainnet/IronBank.t.sol
  packages/protocol/test/forking/optimism/IronBankOptimism.t.sol
Labels: Smart Contracts

#241 Hundred as Lending Provider
  packages/protocol/foundry.toml
  packages/protocol/src/helpers/ProxyReceiver.sol
  packages/protocol/src/interfaces/compoundV2/IProxyReceiver.sol
  packages/protocol/src/providers/arbitrum/HundredArbitrum.sol
  packages/protocol/src/providers/gnosis/HundredGnosis.sol
  packages/protocol/src/providers/optimism/HundredOptimism.sol
  packages/protocol/src/providers/polygon/HundredPolygon.sol
  packages/protocol/test/forking/ForkingSetup.sol
  packages/protocol/test/forking/arbitrum/HundredArbitrum.t.sol
  packages/protocol/test/forking/gnosis/HundredGnosis.t.sol
  packages/protocol/test/forking/optimism/HundredOptimism.t.sol
  packages/protocol/test/forking/polygon/HundredPolygon.t.sol
Labels: Smart Contracts

#249 Agave as Lending Provider
  packages/protocol/src/providers/gnosis/AgaveGnosis.sol
  packages/protocol/test/forking/gnosis/AgaveGnosis.t.sol
Labels: Smart Contracts

#246 Radiant as lending provider
  packages/protocol/src/providers/arbitrum/RadiantArbitrum.sol
  packages/protocol/test/forking/arbitrum/RadiantArbitrum.t.sol
Labels: Smart Contracts

#244 0vix as lending provider
  packages/protocol/src/interfaces/Ovix/ICToken.sol
  packages/protocol/src/libraries/LibOvix.sol
  packages/protocol/src/providers/polygon/OvixPolygon.sol
  packages/protocol/test/forking/polygon/Ovix.t.sol
Labels: Smart Contracts

#252 Protocol/fix/cs swapper slippage too high
  packages/protocol/src/FujiOracle.sol
  packages/protocol/src/interfaces/ISwapper.sol
  packages/protocol/src/libraries/LibActionBundler.sol
  packages/protocol/src/mocks/MockSwapper.sol
  packages/protocol/src/swappers/UniswapV2Swapper.sol
  packages/protocol/test/forking/mainnet/UniswapV2Swapper.t.sol
  packages/protocol/test/mocking/routers/SimpleRouter.t.sol
Labels: Smart Contracts

#259 Align license and pragma
  packages/protocol/src/abstracts/EIP712.sol
  packages/protocol/src/interfaces/dforce/IGenIToken.sol
  packages/protocol/src/interfaces/dforce/IIERC20.sol
  packages/protocol/src/interfaces/dforce/IIETH.sol
  packages/protocol/src/interfaces/morpho/IMorpho.sol
  packages/protocol/src/mocks/MockAddrMapper.sol
  packages/protocol/src/mocks/MockRebalancerManager.sol
  packages/protocol/src/swappers/UniswapV2Swapper.sol
Labels: Smart Contracts

#257 Balancer flashloan provider
  packages/protocol/src/flashloans/FlasherBalancer.sol
  packages/protocol/src/interfaces/balancer/IBalancerVault.sol
  packages/protocol/src/interfaces/balancer/IFlashLoanRecipient.sol
  packages/protocol/src/interfaces/balancer/IProtocolFeesCollector.sol
  packages/protocol/test/forking/arbitrum/FlasherBalancerArbitrum.t.sol
  packages/protocol/test/forking/gnosis/FlasherBalancerGnosis.t.sol
  packages/protocol/test/forking/mainnet/FlasherBalancer.t.sol
  packages/protocol/test/forking/optimism/FlasherBalancerOptimism.t.sol
  packages/protocol/test/forking/polygon/FlasherBalancerPolygon.t.sol
Labels: Smart Contracts

#258 Connext router bridging slippage
  packages/protocol/src/abstracts/BaseRouter.sol
  packages/protocol/src/routers/ConnextRouter.sol
  packages/protocol/test/forking/ForkingSetup.sol
  packages/protocol/test/forking/goerli/ConnextRouter.t.sol
  packages/protocol/test/forking/optimism-goerli/ConnextRouter.t.sol
Labels: Smart Contracts

#272 Improve code comments swappers
  packages/protocol/src/interfaces/ISwapper.sol
  packages/protocol/src/interfaces/uniswap/IUniswapV2Router01.sol
  packages/protocol/src/interfaces/uniswap/IUniswapV2Router02.sol
  packages/protocol/src/mocks/MockSwapper.sol
  packages/protocol/src/swappers/UniswapV2Swapper.sol
Labels: Smart Contracts

#267 Improve code comments in Vault and Swapper
  packages/protocol/src/FujiOracle.sol
  packages/protocol/src/RebalancerManager.sol
  packages/protocol/src/abstracts/BaseVault.sol
  packages/protocol/src/abstracts/EIP712.sol
  packages/protocol/src/abstracts/PausableVault.sol
  packages/protocol/src/abstracts/VaultDeployer.sol
  packages/protocol/src/access/CoreRoles.sol
  packages/protocol/src/access/SystemAccessControl.sol
  packages/protocol/src/interfaces/IFujiOracle.sol
  packages/protocol/src/interfaces/IPausableVault.sol
  packages/protocol/src/interfaces/IRebalancerManager.sol
  packages/protocol/src/interfaces/ISwapper.sol
  packages/protocol/src/interfaces/IVault.sol
  packages/protocol/src/interfaces/IVaultFactory.sol
  packages/protocol/src/interfaces/IVaultPermissions.sol
  packages/protocol/src/interfaces/uniswap/IUniswapV2Router01.sol
  packages/protocol/src/interfaces/uniswap/IUniswapV2Router02.sol
  packages/protocol/src/libraries/LibBytes.sol
  packages/protocol/src/libraries/LibSSTORE2.sol
  packages/protocol/src/mocks/MockOracle.sol
  packages/protocol/src/mocks/MockRebalancerManager.sol
  packages/protocol/src/mocks/MockSwapper.sol
  packages/protocol/src/swappers/UniswapV2Swapper.sol
  packages/protocol/src/vaults/VaultPermissions.sol
  packages/protocol/src/vaults/borrowing/BorrowingVault.sol
  packages/protocol/src/vaults/borrowing/BorrowingVaultFactory.sol
  packages/protocol/src/vaults/yield/YieldVault.sol
  packages/protocol/src/vaults/yield/YieldVaultFactory.sol
Labels: Smart Contracts

#269 Improve code comments in IAddrmapper
  packages/protocol/src/helpers/AddrMapper.sol
  packages/protocol/src/interfaces/IAddrMapper.sol
  packages/protocol/src/mocks/MockAddrMapper.sol
Labels: Smart Contracts

#273 Improve code comments in IFlasher and derivatives
  packages/protocol/src/abstracts/BaseFlasher.sol
  packages/protocol/src/flashloans/FlasherAaveV3.sol
  packages/protocol/src/flashloans/FlasherBalancer.sol
  packages/protocol/src/flashloans/FlasherEuler.sol
  packages/protocol/src/mocks/MockFlasher.sol
Labels: Smart Contracts
