Repository Fujicracy/fuji-v2, pull requests merged in 2023-06, with the labels that each got.

#572 Setting checks maxltv liqratio
  packages/protocol/src/abstracts/BaseVault.sol
  packages/protocol/src/vaults/borrowing/BorrowingVault.sol
  packages/protocol/test/mocking/vaults/Vault.t.sol
Labels: Smart Contracts

#569 Onboarding changes
  packages/frontend/components/Borrow/Borrow.tsx
  packages/frontend/components/Onboarding/DisclaimerModal.tsx
  packages/frontend/components/Onboarding/ExploreCarousel.tsx
  packages/frontend/components/Shared/Header/Header.tsx
  packages/frontend/helpers/auth.ts
  packages/frontend/pages/_app.tsx
  packages/frontend/store/auth.store.ts
  packages/frontend/tests/e2e/specs/account-spec.ts
  packages/frontend/tests/e2e/specs/borrow.spec.ts
  packages/frontend/tests/e2e/specs/markets.spec.ts
  packages/frontend/tests/e2e/support.js
Labels: Front End

#441 APY chart
  packages/frontend/components/Borrow/Analytics/APYChartTooltip.tsx
  packages/frontend/components/Borrow/Analytics/AnalyticsHeader.tsx
  packages/frontend/components/Borrow/Analytics/InfoBlock.tsx
  packages/frontend/components/Borrow/Analytics/PoolInfo.tsx
  packages/frontend/components/Borrow/Header.tsx
  packages/frontend/components/Borrow/Overview/Analytics.tsx
  packages/frontend/components/Borrow/Overview/Container.tsx
  packages/frontend/components/Borrow/Overview/Details.tsx
  packages/frontend/components/Borrow/Overview/LTVProgressBar.tsx
  packages/frontend/components/Borrow/Overview/Overview.tsx
  packages/frontend/components/Borrow/Overview/OverviewTab.tsx
  packages/frontend/components/Borrow/Overview/Title.tsx
  packages/frontend/components/Borrow/Wrapper.tsx
  packages/frontend/components/Positions/MyPositionsSummary.tsx
  packages/frontend/components/Positions/PositionYieldsModal.tsx
  packages/frontend/components/Shared/Charts/APYChart.tsx
  packages/frontend/components/Shared/Charts/EmptyState.tsx
  packages/frontend/components/Shared/ConfirmationTransaction/AssetBox.tsx
  packages/frontend/components/Shared/Filters/PeriodOptions.tsx
  packages/frontend/components/Shared/TabChip.tsx
  packages/frontend/components/Shared/TabSwitch.tsx
  packages/frontend/components/Shared/Tooltips/APRTooltip.tsx
  packages/frontend/components/Shared/Tooltips/TooltipWrapper.tsx
  packages/frontend/components/Shared/Tooltips/index.ts
  packages/frontend/constants/common.ts
  packages/frontend/constants/ui.ts
  packages/frontend/helpers/charts.ts
  packages/frontend/helpers/values.ts
  packages/frontend/package.json
  packages/frontend/public/assets/images/shared/chart.svg
  packages/sdk/src/constants/common.ts
  packages/sdk/src/entities/BorrowingVault.ts
  packages/sdk/src/types/LendingProvider.ts
  packages/sdk/src/types/LlamaResponses.ts
  yarn.lock
Labels: Front End

#577 Fix compoundV3 get balance of base asset
  packages/protocol/src/providers/mainnet/CompoundV3.sol
  packages/protocol/test/forking/ForkingSetup.sol
  packages/protocol/test/forking/mainnet/CompoundV3cWETH.t.sol
Labels: Bug, Smart Contracts

#575 Add transfer fee in flasher balancer
  packages/protocol/src/flashloans/FlasherBalancer.sol
Labels: Smart Contracts

#581 Chainlink computed price feed
  packages/protocol/src/helpers/ChainlinkComputedFeed.sol
Labels: Smart Contracts

#583 Internal testing 3
  packages/frontend/components/Borrow/Borrow.tsx
  packages/frontend/components/Borrow/Wrapper.tsx
  packages/frontend/constants/common.ts
  packages/frontend/helpers/navigation.ts
  packages/frontend/pages/_app.tsx
  packages/frontend/pages/borrow.tsx
  packages/frontend/store/borrow.store.ts
Labels: Front End

#591 Guarded launch fixes
  packages/frontend/components/App/Header/AccountModal/HistoryItem.tsx
  packages/frontend/components/Borrow/VaultSelect/Vault.tsx
  packages/frontend/components/Borrow/VaultSelect/VaultSelect.tsx
  packages/frontend/components/Positions/EmptyState.tsx
  packages/frontend/components/Positions/MyPositionsBorrowTable.tsx
Labels: Front End

#592 Guarded launch fixes 2
  packages/frontend/components/Borrow/Overview/Title.tsx
  packages/frontend/components/Borrow/VaultSelect/Vault.tsx
  packages/frontend/components/Borrow/VaultSelect/VaultSelect.tsx
  packages/frontend/components/Borrow/Wrapper.tsx
  packages/frontend/components/Markets/MarketsTable.tsx
  packages/frontend/components/Markets/MarketsTableRow.tsx
  packages/frontend/components/Positions/MyPositionsBorrowTable.tsx
  packages/frontend/components/Shared/AprValue.tsx
  packages/frontend/components/Shared/Table/IntegratedProviders.tsx
  packages/frontend/components/Shared/Tooltips/DocsTooltip.tsx
  packages/frontend/helpers/currencies.ts
  packages/frontend/helpers/markets.ts
  packages/frontend/helpers/navigation.ts
  packages/frontend/pages/_app.tsx
  packages/frontend/pages/borrow.tsx
  packages/frontend/store/borrow.store.ts
  packages/frontend/store/markets.store.ts
Labels: Front End

#599 Guarded launch fixes 3
  packages/frontend/components/App/Onboarding/DisclaimerModal.tsx
  packages/frontend/components/Borrow/ConfirmTransaction/ConfirmTransactionModal.tsx
  packages/frontend/components/Shared/AprValue.tsx
  packages/frontend/components/Shared/Table/IntegratedProviders.tsx
  packages/frontend/helpers/markets.ts
  packages/frontend/helpers/positions.ts
  packages/frontend/helpers/values.ts
Labels: Front End

#603 Rebalancers and Flashers deployments
  packages/protocol/deploy-configs/arbitrum.json
  packages/protocol/deploy-configs/gnosis.json
  packages/protocol/deploy-configs/optimism.json
  packages/protocol/deploy-configs/polygon.json
  packages/protocol/deployments/arbitrum/FlasherBalancer
  packages/protocol/deployments/arbitrum/RebalancerManager
  packages/protocol/deployments/optimism/FlasherBalancer
  packages/protocol/deployments/optimism/RebalancerManager
  packages/protocol/deployments/polygon/FlasherBalancer
  packages/protocol/deployments/polygon/RebalancerManager
  packages/protocol/script/RunArbitrum.s.sol
  packages/protocol/script/RunGnosis.s.sol
  packages/protocol/script/RunOptimism.s.sol
  packages/protocol/script/RunPolygon.s.sol
  packages/protocol/script/ScriptPlus.sol
  packages/protocol/script/ScriptUtilities.s.sol
  packages/protocol/src/abstracts/BaseFlasher.sol
  packages/protocol/src/flashloans/FlasherBalancer.sol
Labels: Smart Contracts

#580 Router withdraw eth check address
  packages/protocol/src/abstracts/BaseRouter.sol
  packages/protocol/test/forking/ForkingSetup.sol
Labels: Smart Contracts

#602 Restore undone fixes due to wrong merge
  packages/protocol/src/abstracts/BaseVault.sol
  packages/protocol/src/providers/mainnet/CompoundV3.sol
  packages/protocol/src/vaults/borrowing/BorrowingVault.sol
  packages/protocol/test/forking/ForkingSetup.sol
  packages/protocol/test/forking/mainnet/CompoundV3cWETH.t.sol
  packages/protocol/test/mocking/vaults/VaultRebalancing.t.sol
Labels: Bug, Smart Contracts

#587 Wallet Connect v2
  packages/frontend/helpers/auth.ts
  packages/frontend/package.json
  yarn.lock
Labels: Front End

#606 Handle 0 fees and slippage on cross tx
  packages/frontend/components/Borrow/Fees.tsx
  packages/sdk/src/Sdk.ts
Labels: Front End

#612 Handle chain change error
  packages/frontend/store/auth.store.ts
Labels: Front End

#619 Transaction modal improvements
  packages/frontend/components/App/TransactionModal.tsx
  packages/frontend/components/Positions/MyPositionsBorrowTable.tsx
  packages/frontend/helpers/borrow.ts
  packages/frontend/helpers/history.ts
  packages/frontend/helpers/navigation.ts
  packages/frontend/helpers/positions.ts
  packages/frontend/store/borrow.store.ts
  packages/frontend/store/history.store.ts
Labels: Front End

#620 Borrow chart
  packages/frontend/components/Borrow/Overview/Analytics/Analytics.tsx
  packages/frontend/components/Borrow/Overview/Container.tsx
  packages/frontend/components/Shared/Charts/EmptyState.tsx
  packages/sdk/src/entities/BorrowingVault.ts
Labels: Front End

#616 Connexthandler simplify nonce
  packages/protocol/src/routers/ConnextHandler.sol
  packages/protocol/test/forking/goerli/ConnextRouter.t.sol
Labels: Smart Contracts

#628 Clarify connext delegate requirements
  packages/protocol/src/abstracts/BaseRouter.sol
  packages/protocol/src/routers/ConnextRouter.sol
Labels: Smart Contracts

#627 BaseRouter checkNoBalanceChange for-loop break
  packages/protocol/src/abstracts/BaseRouter.sol
Labels: Smart Contracts

#626 Handleswap clarify receiver and sweeper conditions
  packages/protocol/src/abstracts/BaseRouter.sol
Labels: Smart Contracts

#625 Multiple code quality optimizations
  packages/protocol/src/abstracts/BaseVault.sol
  packages/protocol/src/vaults/borrowing/BorrowingVault.sol
  packages/protocol/src/vaults/borrowing/BorrowingVault2.sol
  packages/protocol/src/vaults/yields/YieldVault.sol
Labels: Smart Contracts

#623 Replace safe approves
  packages/protocol/src/LiquidationManager.sol
  packages/protocol/src/abstracts/BaseRouter.sol
  packages/protocol/src/routers/ConnextHandler.sol
  packages/protocol/src/swappers/UniswapV2Swapper.sol
Labels: Smart Contracts

#615 Beneficiary check in flashloan action baserouter
  packages/protocol/src/abstracts/BaseRouter.sol
Labels: Smart Contracts

#632 Checking connext _to input
  packages/protocol/src/abstracts/BaseRouter.sol
  packages/protocol/src/routers/ConnextRouter.sol
Labels: Smart Contracts

#641 Yieldvault converts shares-assets twice
  packages/protocol/src/abstracts/BaseVault.sol
  packages/protocol/src/vaults/borrowing/BorrowingVault.sol
  packages/protocol/src/vaults/borrowing/BorrowingVault2.sol
  packages/protocol/src/vaults/yields/YieldVault.sol
Labels: Smart Contracts

#637 Borrowing not vulnerable to inflation
  packages/protocol/script/ScriptPlus.sol
  packages/protocol/src/abstracts/BaseVault.sol
  packages/protocol/src/vaults/borrowing/BorrowingVault.sol
  packages/protocol/src/vaults/borrowing/BorrowingVault2.sol
  packages/protocol/src/vaults/yields/YieldVault.sol
  packages/protocol/test/forking/ForkingSetup.sol
  packages/protocol/test/forking/arbitrum/CompoundV3Arbitrum.t.sol
  packages/protocol/test/forking/arbitrum/DForceArbitrum.t.sol
  packages/protocol/test/forking/arbitrum/WePiggyArbitrum.t.sol
  packages/protocol/test/forking/gnosis/AgaveGnosis.t.sol
  packages/protocol/test/forking/mainnet/CompoundV3.t.sol
  packages/protocol/test/forking/mainnet/CompoundV3cWETH.t.sol
  packages/protocol/test/forking/mainnet/DForce.t.sol
  packages/protocol/test/forking/mainnet/IronBank.t.sol
  packages/protocol/test/forking/mainnet/WePiggy.t.sol
  packages/protocol/test/forking/optimism/IronBankOptimism.t.sol
  packages/protocol/test/forking/polygon/CompoundV3Polygon.t.sol
  packages/protocol/test/forking/polygon/DForcePolygon.t.sol
  packages/protocol/test/forking/polygon/SimpleRouter.t.sol
  packages/protocol/test/forking/polygon/WePiggyPolygon.t.sol
  packages/protocol/test/mocking/MockingSetup.sol
  packages/protocol/test/mocking/routers/SimpleRouter.t.sol
  packages/protocol/test/mocking/vaults/Vault.t.sol
  packages/protocol/test/mocking/vaults/VaultPausable.t.sol
  packages/protocol/test/mocking/vaults/VaultRebalancing.t.sol
Labels: Smart Contracts
